export const ACTIONS = {
  AUTHORIZATION: {
    SIGN_IN: 'SIGNIN_ACTION',
    SIGN_UP: ''
  },
  CACHE_INIT: {
    ALL_DICTS: 'INIT_DICTS',
    GAME_SYSTEMS: 'INIT_GAME_SYSTEMS',
    FORMATS: 'INIT_FORMATS',
    COUNTRIES: 'INIT_COUNTRIES',
    CITIES: 'INIT_CITIES',
    PLACES: 'INIT_PLACES',
    ORGANIZERS: 'INIT_ORGANIZERS',
    STATUSES: 'INIT_STATUSES',
    FACTIONS: 'INIT_FACTIONS'
  },
  COMMONS: {
    CURRENT_ACTIVE_EVENT_ID: 'INIT_CURRENT_ACTIVE_EVENT_ID'
  }
}
