export const ACTIONS = {
  AUTHORIZATION: {
    SIGN_IN: 'SIGNIN_ACTION',
    SIGN_UP: ''
  },
  CACHE_INIT: {
    FORMATS: 'INIT_FORMATS',
    COUNTRIES: 'INIT_COUNTRIES',
    CITIES: 'INIT_CITIES',
    PLACES: 'INIT_PLACES',
    ORGANIZERS: 'INIT_ORGANIZERS',
    STATUSES: 'INIT_STATUSES',
    FRACTIONS: 'INIT_FRACTIONS'
  }
}
