export const EVENT_STATUS_CODE = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  SCHEDULED: 'SCHEDULED',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED'
}

export const EVENT_STATUS_MAP = new Map(
  [[EVENT_STATUS_CODE.OPEN, 'Открыт'],
    [EVENT_STATUS_CODE.CLOSED, 'Завершён'],
    [EVENT_STATUS_CODE.SCHEDULED, 'Запланирован'],
    [EVENT_STATUS_CODE.REGISTRATION_OPEN, 'Открыта регистрация'],
    [EVENT_STATUS_CODE.REGISTRATION_CLOSED, 'Регистрация закрыта']]
)
