export const TOURNAMENT_SYSTEM_NAMES = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  SCHEDULED: 'SCHEDULED',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED'
}

export const TOURNAMENT_STATUS_NAMES = new Map(
  [['OPEN', 'Открыт'],
    [TOURNAMENT_SYSTEM_NAMES.CLOSED, 'Завершён'],
    [TOURNAMENT_SYSTEM_NAMES.SCHEDULED, 'Запланирован'],
    [TOURNAMENT_SYSTEM_NAMES.REGISTRATION_OPEN, 'Открыта регистрация'],
    [TOURNAMENT_SYSTEM_NAMES.REGISTRATION_CLOSED, 'Регистрация закрыта']]
)
